### ISSUE TITLE
there are no esm variant distributed.

### ISSUE THREAD

**Issue by jimmywarting** [MattiasBuelens/remote-web-streams#25]
https://github.com/MattiasBuelens/remote-web-streams/blob/7fca0113b6c748343615cf8e98ff6b6d878bf97a/package.json#L6C1-L7C1

trying to import this using CDN instead of npm and it says there is a module variant shipped but there are non on npm.

would you maybe consider distribute this as a ESM-only pkg?
ditch cjs all together? make a major release.

**Comment by MattiasBuelens** [comment]
Woops! Not sure how that happened, since [the Rollup config definitely builds an ESM variant](https://github.com/MattiasBuelens/remote-web-streams/blob/7fca0113b6c748343615cf8e98ff6b6d878bf97a/rollup.config.js#L10-L13). 😅

And you're right, this package is only meaningful inside a browser, so there's no need to ship a CJS variant. I'll look into it. 🙂
